name: ✨ An Epic Development
description: Tracker for an Epic Development

# define the title and assign the default lables, periodically review
title: "[EPIC]: "
labels: ["epic", "admin", "discussion", "triage"]

body:
  # provide brief description about the issue template
  - type: markdown
    attributes:
      value: |
        ✨ Thank you for creating an `EPIC` feature request. Please do add subsequent `STORY` which breaks the epic into smaller chunks.
        The epic issue request may need ⚖ additional `admin` approval and documentation requirements.
  
  - type: textarea
    id: description
    attributes:
      label: Describe and Elaborate the Epic Request
      description: Please elaborate the epic request and add subsequent story issue to track the changes.
      value: |
        <div align = "justify">
        
        **Overview:** Describe the epic new feature/requirement in a few lines.

        ## 📜 Epic Details

        Describe the contents of the epic, its tentative/planned story features, and
        any other relevant details.

        ### ✔ Epic Feature Checkmarks

        Highlight important milestones and deliverables. In addition, highlight additional code
        checks and feature requirements.

        ## 🚀 Story Tracker

        Track the progress of the underlying stories. GitHub provides a progress meter for all the assigned tasks under a
        issues/pr thus makes it easier to track the progress of the epic.

        </div>
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
